// <auto-generated />
using AttendanceProCloudFunctions.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AttendanceProCloudFunctions.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210124203611_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AttendanceProAPI.Models.FileRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("AttendancePercentage")
                        .HasColumnType("real");

                    b.Property<int>("Attended")
                        .HasColumnType("int");

                    b.Property<string>("CourseCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CourseTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CourseYear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Explained")
                        .HasColumnType("int");

                    b.Property<string>("LastAttendance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NonAttended")
                        .HasColumnType("int");

                    b.Property<string>("RegStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudyLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Teaching")
                        .HasColumnType("int");

                    b.Property<float>("UnexcusedAttendancePercentage")
                        .HasColumnType("real");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
