// <auto-generated />
using AttendanceProCloudFunctions.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace AttendanceProCloudFunctions.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("AttendanceProAPI.Models.FileRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<float>("AttendancePercentage")
                        .HasColumnType("real");

                    b.Property<int>("Attended")
                        .HasColumnType("integer");

                    b.Property<string>("CourseCode")
                        .HasColumnType("text");

                    b.Property<string>("CourseTitle")
                        .HasColumnType("text");

                    b.Property<string>("CourseYear")
                        .HasColumnType("text");

                    b.Property<int>("Explained")
                        .HasColumnType("integer");

                    b.Property<string>("LastAttendance")
                        .HasColumnType("text");

                    b.Property<int>("NonAttended")
                        .HasColumnType("integer");

                    b.Property<string>("RegStatus")
                        .HasColumnType("text");

                    b.Property<string>("StudyLevel")
                        .HasColumnType("text");

                    b.Property<int>("Teaching")
                        .HasColumnType("integer");

                    b.Property<float>("UnexcusedAttendancePercentage")
                        .HasColumnType("real");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
